
sentry:
  dsn: "INSERT_DSN_HERE"
  # Example
  # dsn: "http://SECRET@sentry-main-nginx.sentry-main.svc.cluster.local/2"
  environment: production
  release: "1.0.0"
  logLevel: info
  watchNamespaces: "__all__"
  watchHistorical: "1"
  clusterConfigType: auto
    #  kubeconfigPath: "/path/to/kubeconfig"
  monitorCronjobs: "1"
  customDsns: "1"

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # Will replace the default rules
  custom_rules:
   - verbs:
       - get
       - list
       - watch
     apiGroups:
       - 'apps'
       - 'batch'
       - ''
     resources:
       - events
       - jobs
       - deployments
       - replicasets
       - cronjobs
       - pods

resources:
  limits:
    # cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
  requests:
    # cpu: 250m
    memory: 512Mi
    ephemeral-storage: 1Gi
