kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sentry-url
  namespace: sentry-main
spec:
  host: sentry-okd.example.local
  to:
    kind: Service
    name: sentry-main-nginx
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
