apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-credentials
type: Opaque
data:
  username: "YOUR_USERNAME_BASE64_ENCODED"                # echo -n "uname" | base64
  password: "YOUR_GENERATED_TOKEN_IN_GUI_BASE64_ENCODED"  # echo -n "token" | base64